# Generated by Django 5.2.3 on 2025-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_notes',
            field=models.TextField(blank=True, help_text="Notes from the doctor's consultation.", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, help_text='Prescription details provided by the doctor.', null=True),
        ),
    ]
